export enum EnvKey {
  RMQ_URL = "RMQ_URL",

  MEDIA_GRPC_URL = "MEDIA_GRPC_URL",
  MEDIA_SERVER_PORT = "MEDIA_SERVER_PORT",

  MINIO_ENDPOINT = "MINIO_ENDPOINT",
  MINIO_PORT = "MINIO_PORT",
  MINIO_ACCESS_KEY = "MINIO_ACCESS_KEY",
  MINIO_SECRET_KEY = "MINIO_SECRET_KEY",
}
