syntax = "proto3";

package user.v1;

import "auth.proto";

service UserService {
  rpc GetInfo (GetUserInfoPayload) returns (UserInfoResponse);
  rpc GetMe (GetMePayload) returns (UserInfoResponse);
  rpc EditProfile (EditProfilePayload) returns (UserInfoResponse);
}

message GetUserInfoPayload {
  string user_id = 1;
  optional auth.v1.UserInfo user_info = 2;
}

message UserInfoResponse {
  optional string phone = 1;
  optional string name = 2;
  optional string avatar_url = 3;
}

message GetMePayload {
  auth.v1.UserInfo user_info = 1;
}

message EditProfilePayload {
  optional string phone = 1;
  optional string name = 2;
  optional string avatar_url = 3;
  auth.v1.UserInfo user_info = 4;
}

message UserDisplayInfo {
  string id = 1;
  optional string name = 2;
  optional string avatar_url = 3;
}
