version: '3.9'

services:
  rabbit-mq:
    image: rabbitmq:3-management
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: ${RABBITMQ_USER}
      RABBITMQ_DEFAULT_PASS: ${RABBITMQ_PASS}
    networks:
      - backend

  minio:
    image: minio/minio:latest
    volumes:
      - ./s3/data:/data
    ports:
      - ${MINIO_PORT}:9000
      - ${MINIO_PANEL_PORT}:9001
    environment:
      MINIO_ACCESS_KEY: ${MINIO_ACCESS_KEY}
      MINIO_SECRET_KEY: ${MINIO_SECRET_KEY}
      MINIO_USE_SSL: false
    command: server --console-address ":9001" /data/
    healthcheck:
      test: ['CMD', 'curl', '-f', 'http://localhost:9000/minio/health/live']
      interval: 30s
      timeout: 20s
      retries: 3
    networks:
      - backend

  postgres:
    image: postgres:17
    restart: unless-stopped
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    healthcheck:
      test: ["CMD-SHELL", "su -c 'pg_isready -U postgres' postgres"]
      interval: 30s
      timeout: 30s
      retries: 3
    ports:
      - "5433:5432"
    networks:
      - backend

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:9.2.0
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
      - xpack.security.http.ssl.enabled=false
      - xpack.security.transport.ssl.enabled=false
      - ES_JAVA_OPTS=-Xms512m -Xmx512m
    ports:
      - 9200:9200
    networks:
      - backend

  redis:
    image: redis:8.4.0
    restart: unless-stopped
    environment:
      REDIS_PASSWORD: 123123
      REDIS_DATABASES: 16
      REDIS_MAXMEMORY: 512mb
      REDIS_APPENDONLY: "yes"
    volumes:
      - redis-data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "-a", "$REDIS_PASSWORD", "ping"]
      interval: 30s
      timeout: 10s
      retries: 5
    ports:
      - "6380:6379"
    networks:
      - backend

volumes:
  minio-data:
    driver: local

  redis-data:
    driver: local
