export enum EnvKey {
  ACCESS_JWT_SECRET = "ACCESS_JWT_SECRET",
  REFRESH_JWT_SECRET = "REFRESH_JWT_SECRET",

  RMQ_URL = "RMQ_URL",

  AUTH_REDIS_HOST = "REDIS_HOST",
  AUTH_REDIS_PORT = "REDIS_PORT",
  AUTH_REDIS_USER = "REDIS_USER",
  AUTH_REDIS_PASSWORD = "REDIS_PASSWORD",

  AUTH_GRPC_URL = "AUTH_GRPC_URL",
}
