export enum EnvKey {
  RMQ_URL = "RMQ_URL",

  MINIO_ENDPOINT = "MINIO_ENDPOINT",
  MINIO_PORT = "MINIO_PORT",
  MINIO_ACCESS_KEY = "MINIO_ACCESS_KEY",
  MINIO_SECRET_KEY = "MINIO_SECRET_KEY",

  USER_GRPC_URL = "USER_GRPC_URL",
}
