export enum EnvKey {
  ACCESS_JWT_SECRET = "ACCESS_JWT_SECRET",

  RMQ_URL = "RMQ_URL",
  MINIO_ENDPOINT = "MINIO_ENDPOINT",
  MINIO_PORT = "MINIO_PORT",
  MINIO_ACCESS_KEY = "MINIO_ACCESS_KEY",
  MINIO_SECRET_KEY = "MINIO_SECRET_KEY",

  AUTH_GRPC_URL = "AUTH_GRPC_URL",
  USER_GRPC_URL = "USER_GRPC_URL",
  MEDIA_GRPC_URL = "MEDIA_GRPC_URL",
}
