export enum MICROSERVICE_CLIENT_NAMES {
  AUTH_GRPC = "AUTH_GRPC",
  AUTH_RMQ = "AUTH_RMQ",

  USER_GRPC = "USER_GRPC",

  MEDIA_GRPC = "MEDIA_GRPC",

  ADDRESS_GRPC = "ADDRESS_GRPC",

  SELLER_APPLICATION_GRPC = "SELLER_APPLICATION_GRPC",

  STORE_GRPC = "STORE_GRPC",

  STORE_MODERATION_GRPC = "STORE_MODERATION_GRPC",
}
