import { ADDRESS_SERVICE_NAME } from "./gen/address";
import { AUTH_SERVICE_NAME } from "./gen/auth";
import { MEDIA_SERVICE_NAME } from "./gen/media";
import { SELLER_APPLICATION_SERVICE_NAME } from "./gen/seller-application";
import { STORE_MODERATION_SERVICE_NAME, STORE_SERVICE_NAME } from "./gen/store";
import { USER_SERVICE_NAME } from "./gen/user";

export const GRPC_SERVICE_NAMES = {
  AUTH_SERVICE: AUTH_SERVICE_NAME,
  USER_SERVICE: USER_SERVICE_NAME,
  MEDIA_SERVICE: MEDIA_SERVICE_NAME,
  ADDRESS_SERVICE: ADDRESS_SERVICE_NAME,
  SELLER_APPLICATION_SERVICE: SELLER_APPLICATION_SERVICE_NAME,
  STORE_SERVICE: STORE_SERVICE_NAME,
  STORE_MODERATION_SERVICE: STORE_MODERATION_SERVICE_NAME,
} as const;
