import { GRPC_ERROR_CODE } from "../enums";
import { HttpStatus } from "@nestjs/common";

export const grpcToHttpStatusMapping: Record<GRPC_ERROR_CODE, number | HttpStatus> = {
  [GRPC_ERROR_CODE.OK]: HttpStatus.OK,
  [GRPC_ERROR_CODE.CANCELLED]: 499,
  [GRPC_ERROR_CODE.UNKNOWN]: HttpStatus.INTERNAL_SERVER_ERROR,
  [GRPC_ERROR_CODE.INVALID_ARGUMENT]: HttpStatus.BAD_REQUEST,
  [GRPC_ERROR_CODE.DEADLINE_EXCEEDED]: HttpStatus.GATEWAY_TIMEOUT,
  [GRPC_ERROR_CODE.NOT_FOUND]: HttpStatus.NOT_FOUND,
  [GRPC_ERROR_CODE.ALREADY_EXISTS]: HttpStatus.CONFLICT,
  [GRPC_ERROR_CODE.PERMISSION_DENIED]: HttpStatus.FORBIDDEN,
  [GRPC_ERROR_CODE.RESOURCE_EXHAUSTED]: HttpStatus.TOO_MANY_REQUESTS,
  [GRPC_ERROR_CODE.FAILED_PRECONDITION]: HttpStatus.BAD_REQUEST,
  [GRPC_ERROR_CODE.ABORTED]: HttpStatus.CONFLICT,
  [GRPC_ERROR_CODE.OUT_OF_RANGE]: HttpStatus.BAD_REQUEST,
  [GRPC_ERROR_CODE.UNIMPLEMENTED]: HttpStatus.NOT_IMPLEMENTED,
  [GRPC_ERROR_CODE.INTERNAL]: HttpStatus.INTERNAL_SERVER_ERROR,
  [GRPC_ERROR_CODE.UNAVAILABLE]: HttpStatus.SERVICE_UNAVAILABLE,
  [GRPC_ERROR_CODE.DATA_LOSS]: HttpStatus.INTERNAL_SERVER_ERROR,
  [GRPC_ERROR_CODE.UNAUTHENTICATED]: HttpStatus.UNAUTHORIZED,
};
