version: "3.9"

services:
  api-gateway:
    container_name: api-gateway
    build:
      context: ../..
      dockerfile: ./apps/api-gateway/Dockerfile
    env_file:
      - ../../.env.production
    restart: unless-stopped
    ports:
      - "3000:3000"
    networks:
      - backend
