export const MICROSERVICE_NAME = {
  AUTH_SERVICE: "AUTH_SERVICE",
  NOTIFICATION_SERVICE: "NOTIFICATION_SERVICE",
  USER_SERVICE: "USER_SERVICE",
  PRODUCT_SERVICE: "PRODUCT_SERVICE",
  REVIEW_SERVICE: "REVIEW_SERVICE",
  MEDIA_SERVICE: "MEDIA_SERVICE",
} as const;

export type MicroserviceName = typeof MICROSERVICE_NAME[keyof typeof MICROSERVICE_NAME];
